PlayersManagement/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

app_name = 'PlayersManagement'

urlpatterns = [
    path('', views.PlayersListView.as_view(), name="PlayersList"),
    path('create-player/', login_required(views.CreatePlayer.as_view()), name="CreatePlayer"),
    path('delete-player/<int:id>/<slug>/', login_required(views.PlayerDelete.as_view()), name="DeletePlayer"),
    path('player/<int:id>/<slug>/change/',login_required(views.PlayerUpdate.as_view()), name="UpdatePlayer"),
    path('<int:id>/<slug>/', views.PlayerDetailView.as_view(), name="PlayerDetail"),
]

dartsDBweb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import include, path
from django.views.generic import TemplateView

from .sitemaps import StaticViewSitemap

app_name = 'dartsDBweb'

sitemaps = {
    'static': StaticViewSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="index.html"), name="main"),
    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain"), ),
    # TODO about page
    path('about/', TemplateView.as_view(template_name="index.html"), name="about"),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('playersmanagement/', include('playersmanagement.urls', namespace="playersmanagement")),
    path('score/', include('gamescoring.urls', namespace="gamescoring")),
    path('table/', include('scoretable.urls', namespace="scoretable")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

playersmanagement/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import CreatePlayer, PlayerDelete, PlayerUpdate, PlayerDetailView, PlayersListView

app_name = 'playersmanagement'

urlpatterns = [
    path('', PlayersListView.as_view(), name="PlayersList"),
    path('create-player/', login_required(CreatePlayer.as_view()), name="CreatePlayer"),
    path('delete-player/<int:id>/<slug>/', login_required(PlayerDelete.as_view()), name="DeletePlayer"),
    path('player/<int:id>/<slug>/change/',login_required(PlayerUpdate.as_view()), name="UpdatePlayer"),
    path('<int:id>/<slug>/', PlayerDetailView.as_view(), name="PlayerDetail"),
]

PlayersManagement/models.py
from django.db import models
from django.dispatch import receiver
from django.urls import reverse
from django.utils.text import slugify

import os


def upload_location(instance, filename):
    return f"{instance}/{filename}"


# Create your models here.
class Player(models.Model):
    name        = models.CharField(max_length=10, unique=True)
    slug        = models.SlugField(max_length=10)
    description = models.TextField(blank=True)
    picture     = models.ImageField(upload_to=upload_location,
                                    null=True,
                                    blank=True)
    timestamp   = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated     = models.DateTimeField(auto_now_add=False, auto_now=True)
    active      = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('PlayersManagement:PlayerDetail', args=[self.id, self.slug])

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Player, self).save(*args, **kwargs)


@receiver(models.signals.post_delete, sender=Player)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """
    Deletes file from filesystem
    when corresponding `Player` object is deleted.
    """
    if instance.picture:
        if os.path.isfile(instance.picture.path):
            os.remove(instance.picture.path)


@receiver(models.signals.pre_save, sender=Player)
def auto_delete_file_on_change(sender, instance, **kwargs):
    """
    Deletes old file from filesystem
    when corresponding `Player` object is updated
    with new file.
    """
    if not instance.pk:
        return False
    try:
        old_picture = Player.objects.get(pk=instance.pk).picture
    except Player.DoesNotExist:
        return False
# TODO make it better...
    new_picture = instance.picture
    if not bool(old_picture):
        return False
    if not old_picture == new_picture:
        if os.path.isfile(old_picture.path):
            os.remove(old_picture.path)

playersmanagement/models.py
from django.db import models
from django.dispatch import receiver
from django.urls import reverse
from django.utils.text import slugify

import os


def upload_location(instance, filename):
    return f"{instance}/{filename}"


# Create your models here.
class Player(models.Model):
    name        = models.CharField(max_length=10, unique=True)
    slug        = models.SlugField(max_length=10)
    description = models.TextField(blank=True)
    picture     = models.ImageField(upload_to=upload_location,
                                    null=True,
                                    blank=True)
    timestamp   = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated     = models.DateTimeField(auto_now_add=False, auto_now=True)
    active      = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('playersmanagement:PlayerDetail', args=[self.id, self.slug])

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Player, self).save(*args, **kwargs)


@receiver(models.signals.post_delete, sender=Player)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """
    Deletes file from filesystem
    when corresponding `Player` object is deleted.
    """
    if instance.picture:
        if os.path.isfile(instance.picture.path):
            os.remove(instance.picture.path)


@receiver(models.signals.pre_save, sender=Player)
def auto_delete_file_on_change(sender, instance, **kwargs):
    """
    Deletes old file from filesystem
    when corresponding `Player` object is updated
    with new file.
    """
    if not instance.pk:
        return False
    try:
        old_picture = Player.objects.get(pk=instance.pk).picture
    except Player.DoesNotExist:
        return False
# TODO make it better...
    new_picture = instance.picture
    if not bool(old_picture):
        return False
    if not old_picture == new_picture:
        if os.path.isfile(old_picture.path):
            os.remove(old_picture.path)

PlayersManagement/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, UpdateView, DeleteView
from .models import Player


class PlayersListView(ListView):
    template_name = 'PlayersManagement/list.html'

    def get_queryset(self):
        return Player.objects.all()


class PlayerDetailView(DetailView):
    model = Player
    template_name = 'PlayersManagement/detail.html'

    def get_object(self):
        obj = get_object_or_404(Player, id=self.kwargs['id'])
        return obj


class CreatePlayer(CreateView):
    context_object_name = 'Create'
    model = Player
    fields = ['name', 'description', 'picture', 'active']


class PlayerUpdate(UpdateView):
    context_object_name = 'Update'
    model = Player
    fields = ['name', 'description', 'picture', 'active']

    def get_object(self):
        obj = get_object_or_404(Player, id=self.kwargs['id'])
        return obj

    def get_context_data(self, **kwargs):
        context = super(PlayerUpdate, self).get_context_data(**kwargs)
        context['update_view'] = True
        return context


class PlayerDelete(DeleteView):
    model = Player
    success_url = reverse_lazy('PlayersManagement:PlayersList')

    def get_object(self):
        obj = get_object_or_404(Player, id=self.kwargs['id'])
        return obj

playersmanagement/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, UpdateView, DeleteView
from .models import Player


class PlayersListView(ListView):
    template_name = 'playersmanagement/list.html'

    def get_queryset(self):
        return Player.objects.all()


class PlayerDetailView(DetailView):
    model = Player
    template_name = 'playersmanagement/detail.html'

    def get_object(self):
        obj = get_object_or_404(Player, id=self.kwargs['id'])
        return obj


class CreatePlayer(CreateView):
    context_object_name = 'Create'
    model = Player
    fields = ['name', 'description', 'picture', 'active']


class PlayerUpdate(UpdateView):
    context_object_name = 'Update'
    model = Player
    fields = ['name', 'description', 'picture', 'active']

    def get_object(self):
        obj = get_object_or_404(Player, id=self.kwargs['id'])
        return obj

    def get_context_data(self, **kwargs):
        context = super(PlayerUpdate, self).get_context_data(**kwargs)
        context['update_view'] = True
        return context


class PlayerDelete(DeleteView):
    model = Player
    success_url = reverse_lazy('playersmanagement:PlayersList')

    def get_object(self):
        obj = get_object_or_404(Player, id=self.kwargs['id'])
        return obj

PlayersManagement/templates/PlayersManagement/detail.html
{% extends 'base.html' %}
{% load static %}
{% load tz %}
{% block title %}{{ player.name }}{% endblock %}

{% block content %}
    <div class="card" style="width: 24rem;">
        {% if player.picture %}
            <img class="card-img-top" title="Detail" src="{{ player.picture.url }}" alt="Card image cap">
        {% endif %}
        <div class="card-body">
            <h5 class="card-title">{{ player.name }}</h5>
            <p class="card-text">{{ player.description }}</p>
            <p>{% if player.active %}Active{% else %}Inactive{% endif %}</p>
            <p><small>Created: {% localtime on %}{{ player.timestamp }}{% endlocaltime %}</small></p>
            <!-- Update Player -->
            <a href="{% url 'PlayersManagement:UpdatePlayer' id=player.id slug=player.slug %}" role="button">
                <i class="fas fa-edit" title="Edit"></i>Edit
            </a>
            <!-- Delete Player -->
            <a href="{% url 'PlayersManagement:DeletePlayer' id=player.id slug=player.slug %}" role="button">
                <i class="fas fa-trash-alt" title="Delete"></i>Delete
            </a>
        </div>
    </div>
{% endblock %}

PlayersManagement/templates/PlayersManagement/list.html
{% extends 'base.html' %}
{% block title %}index{% endblock %}

{% block content %}
{% if object_list %}
    <div class="row">
        <h3><b>Current darts</b></h3>
    </div>
    <div class="row">
    {% for player in object_list %}
        <div class="card" style="width: 18rem;">
            {% if player.picture %}
                <img class="card-img-top" title="Detail" src="{{ player.picture.url }}" alt="Card image cap">
            {% endif %}
            <div class="card-body">
                <h5 class="card-title"><a class="" href="{{ player.get_absolute_url }}" title="Detail">{{ player.name }}</a></h5>
                <!-- View Details -->
                <a href="{{ player.get_absolute_url }}" role="button">
                    <i class="fas fa-info-circle" title="Detail"></i> Detail
                </a>
                <!-- Update Player -->
                <a href="{% url 'PlayersManagement:UpdatePlayer' id=player.id slug=player.slug %}"role="button">
                    <i class="fas fa-edit" title="Edit"></i> Edit
                </a>
                <!-- Delete Player -->
                <a href="{% url 'PlayersManagement:DeletePlayer' id=player.id slug=player.slug %}" role="button">
                    <i class="fas fa-trash-alt" title="Delete"></i> Delete
                </a>
            </div>
        </div>
    {% endfor %}
{% endif %}
<!-- Add Player -->
<div class="col">
    <a href="{% url 'PlayersManagement:CreatePlayer' %}" role="button">
        <i class="fas fa-plus-square fa-w-14" title="Add a New Player"></i> Add new darts
    </a>
</div>
</div>
{% endblock %}