dartsDBweb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import include, path
from django.views.generic import TemplateView

from .sitemaps import StaticViewSitemap

app_name = 'dartsDBweb'

sitemaps = {
    'static': StaticViewSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="index.html"), name="main"),
    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain"), ),
    # TODO about page
    path('about/', TemplateView.as_view(template_name="index.html"), name="about"),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('playersmanagement/', include('playersmanagement.urls', namespace="playersmanagement")),
    path('score/', include('gamescoring.urls', namespace="gamescoring")),
    path('table/', include('scoretable.urls', namespace="scoretable")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

scoretable/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import path

from scoretable import views

app_name = 'scoretable'

urlpatterns = [
    path('csv/<category>/', login_required(views.csvweb), name="csvweb"),
    path('zip/', login_required(views.csvzip), name="csvzip"),
    path('download/<slug>/', login_required(views.downloadzip), name="downloadzip"),
    path('deletez/<int:id>/', login_required(views.deletezip), name="deletezip"),
    path('deleteg/<int:id>/', login_required(views.deletegame), name="deletegame"),
    path('editg/<int:id>/', login_required(views.editgame), name="editgame"),
    path('upload_csv/', staff_member_required(views.upload_csv), name="upload_csv"),
    path('<category>/', views.webtables, name="webtables"),
]

scoretable/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class zipcsvfile(models.Model):
    filename        = models.CharField(max_length=32)
    slug            = models.SlugField(max_length=32)
    path            = models.FileField()
    timesdownloaded = models.IntegerField(null=True, blank=True)
    timestamp       = models.DateTimeField(auto_now_add=True, auto_now=False)

    class Meta:
        ordering = ('-timestamp',)

    def __str__(self):
        return self.filename

    def get_absolute_url(self):
        return reverse('scoretable:downloadzip', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.filename)
        super(zipcsvfile, self).save(*args, **kwargs)

scoretable/views.py
from django.conf import settings
from django.contrib import messages
from django.utils.encoding import smart_str
from django.shortcuts import render, HttpResponseRedirect, HttpResponse, get_object_or_404, redirect, reverse

import zipfile
import datetime
import os
import csv

from gamescoring.models import GameNumber, Participant
from gamescoring.backend import ranking
from .models import zipcsvfile
from .maketables import WriteTables, WriteScoreTables, Write_csv, CSV_to_db


def csvweb(request, category=None):
    if category in ['501','BB']:
        rtable, stable, headerrank, headersummary, maxplist = WriteTables(category)
    elif category == 'BBScores':
        rtable, stable, headerrank, headersummary, maxp = WriteScoreTables()
    else:
        messages.warning(request, "Nothing to do")
        return HttpResponseRedirect('/')
    # Create the HttpResponse object with the appropriate CSV header.
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = f'attachment; filename="{category}.csv"'
    writer = csv.writer(response)
    writer.writerow(headerrank)
    writer.writerows(rtable.values())
    writer.writerows([''])
    writer.writerow(headersummary)
    writer.writerows(stable)
    writer.writerows([''])
    return response


def webtables(request, category=None):
    if category in ['501', 'BB']:
        rtable, stable, headerrank, headersummary, maxplist = WriteTables(category)
        stable_title = 'Standings'
    elif category == 'BBScores':
        rtable, stable, headerrank, headersummary, maxplist = WriteScoreTables()
        stable_title = 'Average scores'
    else:
        messages.warning(request, "Nothing to do")
        return HttpResponseRedirect('/')
    context = {'title': f'Tables {category}',
               'maxplist': maxplist,
               'headerrank': headerrank,
               'headersummary': headersummary,
               'maintable': rtable,
               'summarytable': stable,
               'stable_title': stable_title}
    return render(request, 'scoretable/table.html', context)


def csvzip(request):
    path = os.path.join(settings.MEDIA_ROOT, 'files')
    datesuffix = datetime.datetime.now().strftime('_%Y_%m_%d')
    zipfilename = 'DartsTablesCSV' + datesuffix + '.zip'
    longzipfilename = os.path.join(path, zipfilename)
    try:
        if not os.path.exists(path):
            os.makedirs(path)
        zip_archive = zipfile.ZipFile(longzipfilename, 'w')

        for tabletype in ['501', 'BB']:
            rtable, stable, headerrank, headersummary, maxplist = WriteTables(tabletype)
            if len(rtable) > 0:
                outfile = f'DartsTables{tabletype}' + datesuffix + '.csv'
                mf = Write_csv(headerrank, rtable, headersummary, stable)
                zip_archive.writestr(outfile, mf.read())
        if len(rtable) > 0:
            sbb, ssbb, headerscore, headersumscore, maxp = WriteScoreTables()
            outfile = 'DartsTablesBBScores' + datesuffix + '.csv'
            mf = Write_csv(headerscore, sbb, headersumscore, ssbb)
            zip_archive.writestr(outfile, mf.read())
        zip_archive.close()
    except:
        return HttpResponse(status=500)

    z, created = zipcsvfile.objects.get_or_create(filename=zipfilename)
    z.path = smart_str(longzipfilename)
    z.filename = zipfilename
    z.timesdownloaded = 0
    z.save()
    allfiles = zipcsvfile.objects.all()
    context = {'title': 'Download',
               'allfiles': allfiles
               }
    return render(request, 'scoretable/download.html', context)


def downloadzip(request, slug=None):
    f = get_object_or_404(zipcsvfile, slug=slug)
    link = f.path
    response = HttpResponse()
    response['Content-Type'] = 'application/zip'
    response['Content-Disposition'] = f"attachment; filename = {f.filename}"
    response['X-Sendfile'] = smart_str(link)
    f.timesdownloaded += 1
    f.save()
    return response


def editgame(request, id):
    if request.method == "GET":
        q = get_object_or_404(GameNumber, id=id )
        # category = q.category
        # players = q.get_all_players()

        context = {'title': 'Edit',
                   'game': q}
        return render(request, 'scoretable/edit.html', context)
    if request.method == "POST":
        g = get_object_or_404(GameNumber, id=id)
        try:
            requestdict = dict(request.POST)
            selectedplayers = requestdict.get('selectp')
            todb = dict.fromkeys(requestdict.get('selectp'))
            if g.category == 'BB':
                pscores = requestdict.get('pscore')
                pranks = ranking(pscores)
            else:
                pranks = requestdict.get('prank')
                pscores = [None for i in range(len(pranks))]
            z = zip(selectedplayers,pranks,pscores)
            todb = {p:{'rank':int(r),'score':int(s)} for p,r,s in z}
            for p in g.participant_set.all():
                if p.rank != todb[p.player.name]['rank']:
                    q = Participant.objects.get(game=g, player=p.player)
                    q.rank =  todb[p.player.name]['rank']
                    q.save()
                if p.score != todb[p.player.name]['score']:
                    q = Participant.objects.get(game=g, player=p.player)
                    q.score =  todb[p.player.name]['score']
                    q.save()
            return redirect('scoretable:editgame', id=g.id)
        except:
            messages.warning(request, "Sorry, something wrong happened entering data in the database")
            return HttpResponseRedirect('/')


def deletegame(request,id):
    q = get_object_or_404(GameNumber, id=id )
    gcat = q.category
    #todel.delete()
    return HttpResponseRedirect(reverse("scoretable:webtables", kwargs={'category':gcat}))


def deletezip(request,id):
    q = get_object_or_404(zipcsvfile, id=id )
    q.path.delete()
    q.delete()
    qs = zipcsvfile.objects.all().order_by("-timestamp")
    context = {'title': 'Download',
               'allfiles': qs
               }
    return render(request, 'scoretable/download.html', context)


def upload_csv(request):
    if request.method == "POST":
        csvfile = request.FILES['csvfile']
        if not csvfile.name.endswith('.csv'):
            messages.error(request, 'File is not a CSV')
            return HttpResponseRedirect(reverse("scoretable:upload_csv"))
        if CSV_to_db(csvfile):
            messages.success(request, "It worked!")
            return HttpResponseRedirect('/')
        else:
            messages.error(request, "Something wrong happened. Better check the database...")
    return render(request, 'scoretable/uploadcsv.html', {'title': 'Upload'})

scoretable/templates/scoretable/download.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock %}

{% block content %}

<table class="table">
    <thead>
        <tr>
            <th scope="col">File</th>
            <th scope="col">Number of downloads</th>
            <th scope="col">Date</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
    {% for f in allfiles %}
        <tr>
            <td><a title="download" href="{{ f.get_absolute_url }}">{{ f.filename }}</a></td>
            <td>{{ f.timesdownloaded }}</td>
            <td><small>{{ f.timestamp }}</small></td>
            <td><a title="delete" class="btn btn-secondary btn-sm" href="{% url "scoretable:deletezip" f.id %}"><span class="fas fa-trash-alt"></span></a></td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

scoretable/templates/scoretable/edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col">
            <h2>{{ game.category }}</h2>
            {% if game %}
                <form action="{% url 'scoretable:editgame' game.id %}" method="post">
                    {% csrf_token %}

                    {% for p in game.participant_set.all %}
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <div class="input-group-text" style="width: 150px">
                                    {{ p.player.name }}
{#                                    <input type="text" name="selectp" id="selectp-{{ p.player.id }}" value="{{ p.player.name }}" readonly>#}
{#                                    <label style="width: 100px">{{ player.name }}</label>#}
                                </div>
                            </div>
                            {% if game.category == '501' %}
                                <select  name="prank" id="prank-{{ p.id }}">
                                    {% for n in game.participant_set.all %}
                                        <option value="{{ forloop.counter }}" {% if p.rank == forloop.counter %}selected='selected'{% endif %}>
                                            {{ forloop.counter }}
                                        </option>
                                    {% endfor %}
                                </select>

                            {% elif game.category == 'BB' %}
                                <input  type="number" min="0" max="198" required value="{{ p.score }}" name='pscore' id="pscore-{{ p.id }}">
                            {% endif %}
                        </div>
                    {% endfor %}
                    <input type="submit" class="btn btn-primary" value="Save"/>
                </form>
            {% endif %}
        </div>
    </div>
{% endblock %}

scoretable/templates/scoretable/table.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ title }}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col">
            <h2>{{ title }}</h2>
            <hr style="border-top: 2px solid #d9d9d9;">
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6">
            <h3>Games</h3>
            <table class="table" id="games_table">
                <thead>
                <tr>
                    {% for s in headerrank %}
                        <th scope="col">{{ s }}</th>
                    {% endfor %}
                    <th scope="col"></th>
                </tr>
                </thead>
                <tbody>
                {% for k, r in maintable.items %}
                    <tr>
                        {% for s in r %}
                            <td>{{ s }}</td>
                        {% endfor %}
                        <td>
                            <a href="{% url "scoretable:editgame" k %}" class="btn btn-light btn-sm" role="button">
                                <i class="fas fa-edit" title="edit" aria-hidden="true"></i>
                            </a>
                            <a href="{% url "scoretable:deletegame" k %}" class="btn btn-light btn-sm" role="button" onclick="return confirm('Are you sure?')">
                                <i class="far fa-trash-alt" title="delete" aria-hidden="true"></i>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    <div class="col-sm-1">
    </div>
        <div class="col-lg-5">
            <h3>{{ stable_title }}</h3>
            <table class="table" id="standing_table">
                <thead>
                <tr>
                    {% for s in headersummary %}
                        <th scope="col">{{ s }}</th>
                    {% endfor %}
                </tr>
                </thead>
                <tbody>
                {% for r in summarytable %}
                    <tr>
                        {% for s in r %}
                            <td>{{ s }}</td>
                        {% endfor %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>


{% endblock content %}

{% block js %}
    <script src="{% static 'scoretable/datatables.js' %}"></script>
{% endblock js %}

scoretable/templates/scoretable/uploadcsv.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock %}

{% block content %}
    <h3>Upload a csv file:</h3>
    <form action="{% url "scoretable:upload_csv" %}" method="post" enctype="multipart/form-data">{% csrf_token %}
        <input type="file" name="csvfile" />
        <input type="submit" value="Upload" />
    </form>
{% endblock %}