PlayersManagement/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

app_name = 'PlayersManagement'

urlpatterns = [
    path('', views.PlayersListView.as_view(), name="PlayersList"),
    path('create-player/', login_required(views.CreatePlayer.as_view()), name="CreatePlayer"),
    path('delete-player/<int:id>/<slug>/', login_required(views.PlayerDelete.as_view()), name="DeletePlayer"),
    path('player/<int:id>/<slug>/change/',login_required(views.PlayerUpdate.as_view()), name="UpdatePlayer"),
    path('<int:id>/<slug>/', views.PlayerDetailView.as_view(), name="PlayerDetail"),
]

dartsDBweb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import include, path
from django.views.generic import TemplateView

from .sitemaps import StaticViewSitemap

app_name = 'dartsDBweb'

sitemaps = {
    'static': StaticViewSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="index.html"), name="main"),
    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain"), ),
    # TODO about page
    path('about/', TemplateView.as_view(template_name="index.html"), name="about"),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('playersmanagement/', include('playersmanagement.urls', namespace="playersmanagement")),
    path('score/', include('gamescoring.urls', namespace="gamescoring")),
    path('table/', include('scoretable.urls', namespace="scoretable")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gamescoring/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from gamescoring import views

app_name = 'gamescoring'

urlpatterns = [
    path('ScoreConfirm/', login_required(views.ScoreConfirm), name="ScoreConfirm"),
    path('SaveScore/', login_required(views.SaveScore), name="SaveScore"),
    path('NewScore/', login_required(views.NewScore), name="NewScore"),
    path('<category>/', login_required(views.EnterScore), name="EnterScore"),
]

scoretable/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import path

from scoretable import views

app_name = 'scoretable'

urlpatterns = [
    path('csv/<category>/', login_required(views.csvweb), name="csvweb"),
    path('zip/', login_required(views.csvzip), name="csvzip"),
    path('download/<slug>/', login_required(views.downloadzip), name="downloadzip"),
    path('deletez/<int:id>/', login_required(views.deletezip), name="deletezip"),
    path('deleteg/<int:id>/', login_required(views.deletegame), name="deletegame"),
    path('editg/<int:id>/', login_required(views.editgame), name="editgame"),
    path('upload_csv/', staff_member_required(views.upload_csv), name="upload_csv"),
    path('<category>/', views.webtables, name="webtables"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

{% include 'header.html' %}

<body>
    {% include 'navbar.html' %}

    <main role="main" class="container-fluid">
    <br>
        {% include 'messages_display.html' %}
        <div class="container-fluid mt-4">
            {% block content %}hello{% endblock %}
        </div>
    <br>
    </main> <!-- /container -->
    {% include 'footer.html' %}

    {% include 'js.html' %}

    {% block js %}{% endblock js %}

</body>
</html>

templates/footer.html
{% load static %}
<div class='footer'>
    <footer>
        <hr class="lga">
        <div class="container-fluid">
            <p>
                <a href="mailto:lgalarno@outlook.com">
                    &copy; 2018 Luc Galarneau
                </a>
                <a href="https://github.com/lgalarno">
                    <img src="{% static 'images/GitHub-Mark/PNG/GitHub-Mark-32px.png' %}" width="16" height="16" class="d-inline-block" alt="GitHub">
                </a>
            </p>
        </div>
    </footer>
</div>

templates/header.html
{% load static %}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" type="text/css" href="{% static 'css/fontawesome_all.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/dataTables.bootstrap4.min.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>LGdartsDBweb {% block title %}{% endblock %}</title>
</head>

templates/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col text-center">
            {% if request.user.is_authenticated %}
                <h2>Welcome {{ request.user }}</h2>
            {% else %}
                <h2>You need to <a href="{% url 'login' %}">log in</a> before making changes!</h2>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/js.html
{% load static %}

<script type="text/javascript" charset="utf8" src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<!--Precompiled for Bootstrap 4 -->
<script type="text/javascript" charset="utf8" src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
 <!--datatables with Bootstrap 4 -->
<script type="text/javascript" charset="utf8" src="{% static 'js/jquery.dataTables.min.js' %}"></script>
<script type="text/javascript" charset="utf8" src="{% static 'js/dataTables.bootstrap4.min.js' %}"></script>

templates/messages_display.html
{% if messages %}
    <div class="messages">
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                {% if "html_safe" in message.tags %}
                    {{ message|safe }}
                {% else %}
                    {{ message }}
                {% endif %}</li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light lga">
    <a class="navbar-brand" href="/"><img src="{% static 'images/dartboard.jpg' %}" height="30" class="d-inline-block align-top rounded-circle" alt="LGdartsDBweb"> LGdartsDBweb</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
{#            TODO: Dropdown with list and add player ?#}
            <li class="nav-item">
                <a class="nav-link" href="{% url "playersmanagement:PlayersList" %}">Players Management</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">New Result</a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'gamescoring:EnterScore' category='BB' %}">BB</a>
                    <a class="dropdown-item" href="{% url 'gamescoring:EnterScore' category='501' %}">501</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Tables</a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'scoretable:webtables' category='501' %}">501</a>
                    <a class="dropdown-item" href="{% url 'scoretable:webtables' category='BB' %}" onclick="window.open('{% url 'scoretable:webtables' category='BBScores' %}');">BB</a>
                    <a class="dropdown-item" href="{% url 'scoretable:webtables' category='501' %}" onclick="window.open('{% url 'scoretable:webtables' category='BB' %}');window.open('{% url 'scoretable:webtables' category='BBScores' %}');">All</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown02" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">CSV</a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" title="make csv files" href="{% url "scoretable:csvzip" %}" >CSV in a Zip</a>
                    <a class="dropdown-item" title="make csv files" href="{% url 'scoretable:csvweb' category='501' %}">501</a>
                    <a class="dropdown-item" title="make csv files" href='{% url 'scoretable:csvweb' category='BB' %}'>BB Ranks</a>
                    <a class="dropdown-item" title="make csv files" href="{% url 'scoretable:csvweb' category='BBScores' %}">BB Scores</a>
                    <a class="dropdown-item" title="upload csv files" href="{% url 'scoretable:upload_csv' %}" >Upload initial CSV</a>
                </div>
            </li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          {% if request.user.is_authenticated %}
              <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Log out</a></li>
          {% endif %}


        {% if not request.user.is_authenticated and not "login" in request.get_full_path %}
            <form class="form-inline my-2 my-lg-0" action="{% url 'login' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="next" value="{% if request.GET.next %}{{ request.GET.next }}{% else %}/{% endif %}" />
                <div class="form-group">
                    <input class="form-control mr-sm-2" type="text" name='username' placeholder='Username'>
                </div>
                <div class="form-group">
                    <input class="form-control mr-sm-2" type="password" name='password' placeholder='Password'>
                </div>
                <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Log in</button>
            </form>
        {% endif %}
        </ul>
    </div>
</nav>